Fix#234
takamatsu-city/opendata pull request #239
Opened 2023-10-20 08:07 UTC by naogify

2023-10-20 09:17 UTC, phanect requested changes

2023-10-20 09:17 UTC, phanect commented on tests/csv2geojson.test.js
> +    const csvData = `緯度,経度,name\n35.681236,139.767125,東京駅\n35.658581,139.745433,品川駅`;
![review:must](https://img.shields.io/badge/review-must-critical.svg)

テンプレートリテラルの中で backtick と `$` 以外のエスケープシーケンスって使えましたっけ? 確か `\n` はエスケープできなかったような記憶があります。

2023-10-20 09:17 UTC, phanect commented on src/csv-to-geojson.js
> +    callback
![review:In My Opinion](https://img.shields.io/badge/review-imo-yellow.svg)
こんな感じでコールバック関数化を回避できるかと思います。

```js
const csvToGeoJSON = async (csvString) => {
  return new Promise((resolve) => {
    // ...
    csv2geojson.csv2geojson(csvString, { /* ... */ }, () => resolve()); 
  });
 }
```

2023-10-23 00:27 UTC, keichan34 requested changes

2023-10-23 00:27 UTC, keichan34 commented on src/csv-to-geojson.js
> +  const headers = parse(csvString, {
今回は大きいファイルが特に無いので問題ないのですが、この実装だと1つ目のヘッダー行しか使わないに関わらず、ファイル全体をパースしている。 csv-parse は stream API で使えるので、

```javascript
const readStream = fs.createReadStream(pathToFile);
const reader = (csv-parse.parse)(readStream, { ..options.. });
for await (const line of reader) {
  // line でなにかする
  break;
}
```

csv2geojson 自体は文字列（つまり、全てを読み込まないといけない）を想定しているのでわざわざこれしなくてもいいと思います。大きめのファイルを処理するときに覚えておけばと思います（システムメモリの 1/3 ぐらいのファイル？）

2023-10-23 00:27 UTC, keichan34 commented on src/csv-to-geojson.js
> +  if (headers.includes('経度')) lonField = '経度';
csv2geojson は [latitude / longitude だけではない](https://github.com/mapbox/csv2geojson/blob/gh-pages/index.js#L6-L22) ので、その guessHeader の仕組みを再現するか、日本語の緯度経度あればそれ設定する、なければ undefined のままにする、のどっちかにした方がいいと思います。

2023-10-23 00:27 UTC, keichan34 commented on tests/csv2geojson.test.js
> +    const csvData = `緯度,経度,name\n35.681236,139.767125,東京駅\n35.658581,139.745433,品川駅`;
`\n` は backtick 内でも大丈夫そうですね

```
> a = `hello\nthere`;
'hello\nthere'
> console.log(a)
hello
there
```

backtick は改行も大丈夫なので

```
const csvData = `緯度,経度,name
35.681236,139.767125,東京駅
35.658581,139.745433,品川駅
`;
```

みたいな表記でもいいけど、インデントレベルを保つために各行の頭にスペースが入って、取り除くのがちょっと大変だから今の `\n` でいいかなと思います。。

2023-10-23 09:10 UTC, phanect commented on tests/csv2geojson.test.js
> +    const csvData = `緯度,経度,name\n35.681236,139.767125,東京駅\n35.658581,139.745433,品川駅`;
おっと、大丈夫でしたか、失礼しました。
であればこの件は問題ないですね。

2023-10-24 06:12 UTC, naogify commented on src/csv-to-geojson.js
> +    callback
@phanect 
ありがとうございます。`new Promise` を使うように修正しました。`resolve({ data })` 、`reject({ err })` で値を返すようにしました。

2023-10-24 06:16 UTC, naogify commented on src/csv-to-geojson.js
> +  const headers = parse(csvString, {
@keichan34 

確かにパースする必要なかったので、正規表現で1行目を取得するように変更したのですが、どうでしょうか？
改行コードは `\n` `\r\n` `\r` に対応しました。

https://github.com/takamatsu-city/opendata/blob/e33bd64fafe1b03d6da94c99aa5c5a0bbc493092/src/csv-to-geojson.js#L12

2023-10-24 06:20 UTC, naogify commented on src/csv-to-geojson.js
> +  if (headers.includes('経度')) lonField = '経度';
@keichan34 
ありがとうございます。日本語の緯度経度がなければデフォルトの設定を使うように修正しました。

https://github.com/takamatsu-city/opendata/blob/e33bd64fafe1b03d6da94c99aa5c5a0bbc493092/src/csv-to-geojson.js#L8-L30

2023-10-24 07:09 UTC, phanect commented on src/csv-to-geojson.js
> +          reject({ err });
一般にはエラーオブジェクトは `reject(err)` のように渡した方が、そのままエラーとして throw されるので良いと思いますが、どうでしょうか。

2023-10-24 07:51 UTC, keichan34 requested changes
細かいところですがよろしくおねがいします。

2023-10-24 07:51 UTC, keichan34 commented on src/csv-to-geojson.js
> +        latfield: '緯度',
ここは上書きする必要ないので、
```
options.latfield = ..
```
みたいにするとちょっときれいに見るようになります

2023-10-24 07:51 UTC, keichan34 commented on src/csv-to-geojson.js
> +        if (err) {
ここはすごい細かいのですが、

```
if (err) {
  reject(err);
  return
}
resolve(data);
```

をすると、else内の階層を1個節約できます。

また、新しいobjectにラッピングする必要は無いのかなと思いますが、いかがでしょう。。？

2023-10-25 01:46 UTC, naogify commented on src/csv-to-geojson.js
> +          reject({ err });
@phanect 
確かに、エラーとして `throw` されるので、オブジェクトとして取得する必要はないですね。ありがとうございます。修正しました。

2023-10-25 01:48 UTC, naogify commented on src/csv-to-geojson.js
> +        latfield: '緯度',
ありがとうございます。修正しました。

2023-10-25 01:49 UTC, naogify commented on src/csv-to-geojson.js
> +        if (err) {
@keichan34 
確かに簡潔になりますね。data, err をそれぞれオブジェクトとして取得する必要はないですね。修正しました!

2023-10-25 02:10 UTC, phanect approved these changes
LGTM 👍

2023-10-25 02:11 UTC, keichan34 approved these changes
ありがとうございました！

2023-10-25 02:19 UTC, merged