PAT を使用して README を Push する
takamatsu-city/opendata pull request #242
Opened 2023-10-31 08:22 UTC by naogify

2023-10-31 23:54 UTC, keichan34 requested changes
PAT使うことによって、再起可能になって無限ループになる可能性があるので、そこら辺を確認してください。例えば、「今のコミット名が Update README だけどもう一度 Update README コミットを作ろうとするとエラーになる」など。
他のプロジェクトで https://github.com/EndBug/add-and-commit こちら使ってるので、もしかしたらこの方が楽かも。
よろしくお願いしますー。

2023-11-01 03:48 UTC, naogify commented
@keichan34 

ありがとうございます。以下のように修正しました。

- `paths-ignore: README.md`を使用して GitHub Action から README 更新時に、ステータスチェックを発火させないように修正
- `EndBug/add-and-commit@v7` を使用して `push` するよう修正
- 以下の理由から `push` 時ではなく、`checkout` 時にパーソナルアクセストークンを使用するように修正
  -  `EndBug/add-and-commit@v7`の仕様
  - `push`時に`GITHUB_TOKEN`環境変数で渡すのでは上手く渡せなかったため（`token` で渡せば良かった?）


修正内容のコードを反映したテストリポジトリでの、PR のURL も共有します。

https://github.com/naogify/opendata/pull/19

2023-11-09 06:36 UTC, naogify commented
@keichan34 
こちらREADME も push するように修正しました。サンプルのPRは以下になります。

**◼️新規データの追加**
https://github.com/naogify/opendata/pull/53

**◼️既存データの更新**
https://github.com/naogify/opendata/pull/52

**◼️データ以外の更新**
https://github.com/naogify/opendata/pull/54

2023-11-24 02:41 UTC, keichan34 approved these changes

2023-11-24 02:42 UTC, merged