add test data
takamatsu-city/opendata pull request #339
Opened 2024-01-26 01:05 UTC by naogify

2024-01-26 03:59 UTC, phanect approved these changes

2024-01-26 04:31 UTC, keichan34 reviewed
papaparse と csv2geojson 両方使ってるのはちょっと冗長的な感じをしますね、、。
csv2geojson を使わないないといけない理由はなんですか？その動きをpapaparseで実装するために何が必要？

2024-01-26 06:32 UTC, naogify commented
@keichan34 
> csv2geojson を使わないないといけない理由はなんですか？その動きをpapaparseで実装するために何が必要？

確かにライブラリを使わずに GeoJSON に変換した方が冗長さがなくなりますね。（Point、Lineも Polygon もとなるとライブラリを使った方が良いかもですが、今回は Point データだけなので自前で変換しても良さそう）

2024-01-26 06:38 UTC, naogify commented
@keichan34 
こちら csv2geojson を使わないように修正しました。お手すきの時に確認お願いしても良いでしょうか？

2024-01-29 02:52 UTC, keichan34 requested changes
細かいですが修正をお願いします。。

レビューしているときにpapaparseのドキュメンテーションとcsv2geojsonを両方確認しましたが、ヘッダー周りの実装がちょっとcsv2geojsonからそれているのと、同名のヘッダーが複数あるときに挙動がちょっとわからないので、問題になったらそこら辺を改善する必要あるかもしれない。

2024-01-29 02:52 UTC, keichan34 commented on src/csv-to-geojson.js
> +        headers.forEach(field => {
ループはfor..ofで対応できるならそれで行きましょう `for (const field of headers)`

2024-01-29 02:52 UTC, keichan34 commented on src/csv-to-geojson.js
> +          if (latHeaders.includes(field)) {
最初見つかったカラムを使うようにしましょう。 `if (typeof latField !== 'undefined' && latHeaders.includes(field)) {`

2024-01-29 05:28 UTC, naogify commented on src/csv-to-geojson.js
> +        headers.forEach(field => {
こちら修正しました!

2024-01-29 05:30 UTC, naogify commented on src/csv-to-geojson.js
> +          if (latHeaders.includes(field)) {
承知しました。最初に見つかったカラムのみ対応だと以下のようになるかと思い修正したのですが、いかがでしょうか？

```
if (typeof latField === 'undefined' && latHeaders.includes(field)) {
```

2024-01-29 05:32 UTC, naogify commented
@keichan34 
上記のフィードバック対応しました。またお手すきの時に確認お願いしても良いでしょうか？

2024-01-29 05:34 UTC, keichan34 approved these changes
ありがとうございました！

2024-01-30 00:36 UTC, merged