README を GitHub Action で生成する
takamatsu-city/opendata pull request #75
Opened 2023-05-18 09:21 UTC by naogify

2023-05-19 06:47 UTC, keichan34 requested changes

2023-05-19 06:47 UTC, keichan34 commented on .github/workflows/deploy.yml
> +          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
bash の if文ではなくて github actions の if 文（次の `actions/upload-artifact@v3` を参照) で対応してください :bow:

2023-05-19 07:34 UTC, naogify commented on .github/workflows/deploy.yml
> +          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
@keichan34 
こちら以下のように修正しました。またお手すきの時に確認お願いしても良いでしょうか？

```
- name: Update README
  if: github.event_name == 'pull_request'
  run: |
    npm run build-readme
```

2023-07-18 04:19 UTC, keichan34 approved these changes

2023-07-19 01:25 UTC, merged