CSV を Excel ファイルから生成
takamatsu-city/opendata pull request #82
Opened 2023-06-12 07:14 UTC by phanect

現状は CSV のみがリポジトリーに入っている状態だが、CSV を Excel で編集しようとすると文字化けする。
CSV を Excel で取り扱うと混乱を招くため、リポジトリーに Excel ファイルを置き、CSV は Excel ファイルから自動生成の上main ブランチに push されるようにする。

注: 本 PR の main ブランチマージと同時に、リポジトリー上の全ての CSV ファイルが nkf によって変換され、

- Shift_JIS から UTF-8 (BOM なし) への変換
- 半角カタカナから全角カタカナへ変換
- ハイフン系の文字の文字コードの正規化

などが行われる。
具体的な変更内容については、[このコミット](https://github.com/phanect/opendata/commit/8771bdcd5be5661bb8bbbf02996c8b9b598edaa6)を参照のこと。

2023-06-12 08:08 UTC, naogify requested changes

2023-06-12 08:08 UTC, naogify commented on src/build-csv.js
> +  // Remove first column
@phanect 
細かくてすみませんが、opendata の処理では 最初の行を削除する処理をされていない（する必要がない）ので、こちらのコメントは削除お願いしても良いでしょうか？

2023-06-12 09:18 UTC, phanect commented on src/build-csv.js
> +  // Remove first column
おっと、すみません、削除が漏れていました。

2023-06-12 09:22 UTC, phanect commented on src/build-csv.js
> +  // Remove first column
373c5e4 にて修正済みです。

2023-06-13 05:40 UTC, naogify approved these changes
@phanect 
コメント削除ありがとうございます! 高松市さんからの返信を待ってマージしたいと思います。

2023-06-13 06:55 UTC, phanect commented
@naogify CSV ファイル中にある CR (`\r`) が、変な文字列に変換されてしまっていたようでしたので、CSV ファイル中の改行コードを CRLF から LF に変換する処理を挟み、Excel ファイルを再生成しました。

2023-06-20 05:29 UTC, phanect commented
rebase して再 push

2023-06-20 08:47 UTC, merged